# Generated by Django 5.1 on 2024-11-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='prompt',
            field=models.TextField(blank=True, help_text='user prompt', null=True),
        ),
    ]
